sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /kinect_head/depth_registered/points__xx
    max_range: 2.0
    point_subsample: 1
    padding_offset: 0.03
    padding_scale: 3.0
    filtered_cloud_topic: filtered_cloud_head
#  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#    point_cloud_topic: /kinect2/qhd/points
#    max_range: 2.0
#    point_subsample: 1
#    padding_offset: 0.03
#    padding_scale: 3.0
#    filtered_cloud_topic: filtered_cloud_table
