# this should be faster than using point clouds but it requires OpenGL
sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /kinect_head/depth_registered/image_raw
    queue_size: 1
    near_clipping_plane_distance: 0.5
    far_clipping_plane_distance: 2.0
    shadow_threshold: 0.2
    padding_scale: 3.0
    padding_offset: 0.03
    filtered_cloud_topic: filtered_cloud_pr2
